### ISSUE TITLE
Rollup: d3Dispatch is not defined

### ISSUE THREAD

**Issue by Oreonax** [susielu/d3-annotation#11] opened 2017-03-07 16:14 UTC
Hi,

First of all: great work ! I had a successful try with the standalone version. I've try to use it with rollup (I'm a complet newbie with rollup so there is a high probability that the issue is on my side). I get a "Uncaught ReferenceError: d3Dispatch is not defined" in my console.

Here is rollup config file:

```
import { queue } from "d3-queue";
import { event, select, selectAll } from "d3-selection";
import { scaleLinear, scaleIdentity } from "d3-scale";
import { drag } from "d3-drag";
import { json } from "d3-request";
import { annotation, annotationCalloutCircle } from "d3-svg-annotation";

export {
    queue,
    event,
    select,
    selectAll,
    scaleLinear,
    scaleIdentity,
    drag,
    json,
    annotation,
    annotationCalloutCircle
}
```

Which it used with a gulp task:

```
gulp.task('d3-rollup', function() {
    return rollup({
        entry: 'js/custom.d3.js',
        plugins: [
            babel(),
            nodeResolve({ jsnext: true }),
            commonjs(),
            rollup_uglify()
        ]
    }).then(function(bundle) {
        return bundle.write({
            format: 'umd',
            moduleName: 'd3',
            dest: 'js/d3.min.js'
        });
    });
});
```

I just can't get what is wrong. Do I need to import another property ? Have you an idea ?

**Comment by susielu** [comment] 2017-03-08 02:22
Hmmmm I'm definitely not a rollup expert but I'll take a quick look to see if I can find any reason that would be happening.

**Comment by susielu** [comment] 2017-03-08 02:39
I just tried it locally and am able to get it to run properly. Have you tried deleting your node_modules folder and re-installing all the packages and running gulp again? 

The only thing I changed to get it to work was changing `return rollup({` to `return rollup.rollup({` but I assume you've required the file differently so you don't need to do that.

**Comment by yutannihilation** [comment] 2017-03-08 14:03
Hi, I'm encountering the same problem with rollup and babel.

![image](https://cloud.githubusercontent.com/assets/1978793/23706496/bd0bdc08-0451-11e7-8639-96461a176454.png)

Since I'm a very newbie to JavaScript and know little about these toolchains, this is likely just my fault. But, just in case this is useful, I share my code:

repository: https://github.com/yutannihilation/sagittated-calamary/
Github Pages: https://yutannihilation.github.io/sagittated-calamary/

**Comment by susielu** [comment] 2017-03-08 22:13
Hmm really weird. I can't replicate it. @yutannihilation when I clone your repo, install, and then run `npm run build` it worked for me and created a bundle in the docs folder. 

![image](https://cloud.githubusercontent.com/assets/1449837/23726535/6720ec72-0409-11e7-8093-e5e0967e2af0.png)

Can you try with deleting your node_modules and reinstalling?

**Comment by susielu** [comment] 2017-03-08 22:17
I checked the bundle.js and it had been modified and contained all the annotation code.

**Comment by yutannihilation** [comment] 2017-03-08 22:56
Thanks for your quick response! 

Sorry, I've forgot to write that I saw the error on **a browser console**, not the console of Terminal.app or PowerShell.

Yes, rollup seems to succeed in my environment, too. But, when I open it in web browser, I see no annotation and the browser console says there is RefferenceError. I retried after cleaning up `node_modules/`, but the result was the same.

**Comment by susielu** [comment] 2017-03-08 23:04
Aaaahhh that makes sense thanks for the clarification, I'll take a look.

**Comment by yutannihilation** [comment] 2017-03-08 23:18
Thanks!

I slightly suspect that this is a bug of rollup, as there were  some issues related to snake_case and CamelCase in the past.

https://github.com/rollup/rollup/issues/293

**Comment by susielu** [comment] 2017-03-09 17:43
This issue should be resolved in the latest version 1.6.0 Both your rollup configs should work since you have the jsnext flags set to true. 

@yutannihilation thanks for letting me use your repo to test, just an fyi when I was playing around with it, you will need to change this for the annotation to show up because your dates aren't in the same format as the example: 
https://github.com/yutannihilation/sagittated-calamary/blob/master/src/main.js#L66-L66
change to `x: d => x(d.date),` and a few lines down for the accessorsInverse change it to `date: d => x.invert(d.x),`

**Closed by susielu** 2017-03-09 17:43 UTC

**Comment by yutannihilation** [comment] 2017-03-09 22:04
Confirmed. Thanks so much for the fix and your kind advice!

**Comment by Oreonax** [comment] 2017-03-10 09:37
Thanks for your support it works perfectly now !
