### ISSUE TITLE
Note placement

### ISSUE THREAD

**Issue by sashabeep** [susielu/d3-annotation#61] opened 2019-10-17 15:30 UTC
How to always place note above the line? I want to set all the notes like the upper one.
Description on the site does not cover this parameter

![Снимок экрана 2019-10-17 в 18 26 04](https://user-images.githubusercontent.com/5689796/67023509-98ae3a00-f10b-11e9-8dc7-7241166e67c4.png)

**Comment by susielu** [comment] 2019-10-28 17:06
Hmm yes that type of functionality isn't built-in at the moment it is currently auto-placing it, I'll need to add that as a new feature.

**Comment by nobitagit** [comment] 2019-10-28 21:01
Hey @susielu if I understand the request correctly this seems like a very similar request as in https://github.com/susielu/d3-annotation/issues/38, so maybe it's worth closing either one or the other, so the feature request can be tracked by one issue only.

**Comment by susielu** [comment] 2019-10-29 13:23
Great good point, closing this duplicate of #38

**Closed by susielu** 2019-10-29 13:23 UTC
Labels: duplicate, enhancement
